// <auto-generated />
using System;
using FinHome.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinHome.Infrastructure.Data.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250528000000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("FinHome.Domain.Entities.Category", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(400)
                .HasColumnType("nvarchar(400)");

            b.Property<int>("Purpose")
                .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("Name")
                .HasDatabaseName("IX_Categories_Name");

            b.ToTable("Categories", (string)null);
        });

        modelBuilder.Entity("FinHome.Domain.Entities.Person", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<int>("Age")
                .HasColumnType("int");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.HasKey("Id");

            b.HasIndex("Name")
                .HasDatabaseName("IX_People_Name");

            b.ToTable("People", (string)null);
        });

        modelBuilder.Entity("FinHome.Domain.Entities.Transaction", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("int");

            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

            b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("decimal(18,2)");

            b.Property<int>("CategoryId")
                .HasColumnType("int");

            b.Property<DateTime>("Date")
                .HasColumnType("datetime2");

            b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(400)
                .HasColumnType("nvarchar(400)");

            b.Property<int>("PersonId")
                .HasColumnType("int");

            b.Property<int>("Type")
                .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("CategoryId")
                .HasDatabaseName("IX_Transactions_CategoryId");

            b.HasIndex("Date")
                .HasDatabaseName("IX_Transactions_Date");

            b.HasIndex("PersonId")
                .HasDatabaseName("IX_Transactions_PersonId");

            b.HasIndex(new[] { "Date", "Type" })
                .HasDatabaseName("IX_Transactions_Date_Type");

            b.ToTable("Transactions", (string)null);
        });

        modelBuilder.Entity("FinHome.Domain.Entities.Transaction", b =>
        {
            b.HasOne("FinHome.Domain.Entities.Category", "Category")
                .WithMany("Transactions")
                .HasForeignKey("CategoryId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.HasOne("FinHome.Domain.Entities.Person", "Person")
                .WithMany("Transactions")
                .HasForeignKey("PersonId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Category");
            b.Navigation("Person");
        });

        modelBuilder.Entity("FinHome.Domain.Entities.Category", b =>
        {
            b.Navigation("Transactions");
        });

        modelBuilder.Entity("FinHome.Domain.Entities.Person", b =>
        {
            b.Navigation("Transactions");
        });
#pragma warning restore 612, 618
    }
}
